version: "3.8"

services:
  guardian-chrono:
    build: .
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./config.py
        target: /config.py
        read_only: true
    restart: unless-stopped
